name: cmip6-hackathon-demos
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - xarray
  - toolz
  - gcsfs
  - dask
  - distributed
  - pip
  - xhistogram
  - zarr
  - qgrid
  - nc-time-axis
  - cftime
  - pyproj
  - cartopy
  - pip: 
      - git+https://github.com/xgcm/xgcm.git 
